version: '3.8'
services:
  cloud-usage:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - assessment
    environment:
      ASSESSMENT_URL: http://assessment:8081

  assessment:
    image: mrksdh/assessment
    ports:
      - "8081:8080"
