name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package | tee build.log

      - name: Display Maven Logs on Failure
        if: failure()
        run: cat build.log

      - name: Check for Dependency Updates
        run: mvn versions:display-dependency-updates | tee dependency-updates.log

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for Application to be Ready
        run: |
          for i in {1..10}; do
            if docker exec cloud-usage curl -s http://localhost:8080/v1/result; then
              echo "Application is up!"
              break
            fi
            echo "Waiting for application to start..."
            sleep 5
          done

      - name: Test Application with POST Request
        run: |
          docker exec cloud-usage curl -X POST http://localhost:8080/v1/dataset \
          -H "Content-Type: application/json" \
          -d '[
            {
              "customerId": "342a55a3-b138-4665-8351-111b28833d34",
              "workloadId": "53ddf5cf-7a12-4b7f-8751-48757774c0c5",
              "timestamp": 1699872883000,
              "eventType": "start"
            },
            {
              "customerId": "342a55a3-b138-4665-8351-111b28833d34",
              "workloadId": "53ddf5cf-7a12-4b7f-8751-48757774c0c5",
              "timestamp": 1700401984000,
              "eventType": "stop"
            }
          ]'
          sleep 5
          docker exec cloud-usage curl http://localhost:8080/v1/result