name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package | tee build.log

      - name: Display Build Logs
        if: failure()  # Only run if the build step failed
        run: cat build.log

      - name: List Target Directory
        run: ls -l target/  # Check if JAR file was created

      - name: Run Spring Boot Application
        run: |
          nohup java -jar target/cloud-usage-1.0-SNAPSHOT.jar > app.log 2>&1 &
          sleep 15  # Wait for the application to start

      - name: Wait for Application to be Ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/v1/result; then
              echo "Application is up!"
              break
            fi
            echo "Waiting for application to start..."
            sleep 5
          done

      - name: Test POST Request
        run: |
          curl -X POST http://localhost:8080/v1/dataset \
          -H "Content-Type: application/json" \
          -d '[
            {
              "customerId": "342a55a3-b138-4665-8351-111b28833d34",
              "workloadId": "53ddf5cf-7a12-4b7f-8751-48757774c0c5",
              "timestamp": 1699872883000,
              "eventType": "start"
            },
            {
              "customerId": "342a55a3-b138-4665-8351-111b28833d34",
              "workloadId": "53ddf5cf-7a12-4b7f-8751-48757774c0c5",
              "timestamp": 1700401984000,
              "eventType": "stop"
            }
          ]'

      - name: Test GET Request and Validate Result
        run: |
          RESPONSE=$(curl -s -X GET http://localhost:8080/v1/result)
          echo "Response: $RESPONSE"
          EXPECTED='[{"customerId":"342a55a3-b138-4665-8351-111b28833d34","consumption":529101000}]'

          if [[ "$RESPONSE" == *"$EXPECTED"* ]]; then
            echo "Test passed: response matches expected result"
          else
            echo "Test failed: response does not match expected result"
            exit 1
          fi

      - name: Stop Application
        run: pkill -f 'java -jar target/cloud-usage-1.0-SNAPSHOT.jar'

      - name: Output Application Logs on Failure
        if: failure()
        run: cat app.log
